const fs = require('fs');
const path = require('path');

const csvPath = path.resolve(__dirname, '../SEO-METADATA-MASTER.csv');
let csv = fs.readFileSync(csvPath, 'utf8');

if (csv.includes('how-much-does-seo-cost-in-the-uk')) {
  console.log('Already in CSV');
  process.exit(0);
}

const lines = [
  '"https://houserobotics.online/how-much-does-seo-cost-in-the-uk/","How Much Does SEO Cost in the UK?","Blog Article","how much does SEO cost in the UK","SEO pricing UK; SEO cost UK; SEO retainer cost; SEO agency pricing","Informational","How Much Does SEO Cost in the UK? 2026 Pricing Guide","51","Discover typical UK SEO costs in 2026. Explore monthly retainers (£500–£5,000+), one-off audit rates, project pricing, and what drives organic search ROI.","154","https://houserobotics.online/how-much-does-seo-cost-in-the-uk/","index, follow","How Much Does SEO Cost in the UK? 2026 Pricing Guide","Discover typical UK SEO costs in 2026. Explore monthly retainers (£500–£5,000+), one-off audit rates, project pricing, and what drives organic search ROI.","https://houserobotics.online/images/how-much-does-seo-cost-in-the-uk.webp","How Much Does SEO Cost in the UK? 2026 Pricing Guide","Discover typical UK SEO costs in 2026. Explore monthly retainers (£500–£5,000+), one-off audit rates, project pricing, and what drives organic search ROI.","https://houserobotics.online/images/how-much-does-seo-cost-in-the-uk.webp","How Much Does SEO Cost in the UK? (2026 Pricing Guide)","Article, Organization, BreadcrumbList","PASS"',
  '"https://houserobotics.online/what-is-seo-and-why-does-your-business-need-it/","What Is SEO and Why Does Your Business Need It?","Blog Article","what is SEO and why does your business need it","what is SEO; why businesses need SEO; benefits of SEO; organic search growth","Informational","What Is SEO & Why Does Your Business Need It? (Guide)","52","Learn what SEO is and why every business needs organic search visibility to build trust, capture high-intent leads, and drive compounding revenue.","147","https://houserobotics.online/what-is-seo-and-why-does-your-business-need-it/","index, follow","What Is SEO & Why Does Your Business Need It? (Guide)","Learn what SEO is and why every business needs organic search visibility to build trust, capture high-intent leads, and drive compounding revenue.","https://houserobotics.online/images/what-is-seo-and-why-does-your-business-need-it.webp","What Is SEO & Why Does Your Business Need It? (Guide)","Learn what SEO is and why every business needs organic search visibility to build trust, capture high-intent leads, and drive compounding revenue.","https://houserobotics.online/images/what-is-seo-and-why-does-your-business-need-it.webp","What Is SEO and Why Does Your Business Need It?","Article, Organization, BreadcrumbList","PASS"',
  '"https://houserobotics.online/seo-vs-ppc-which-is-better-for-your-business/","SEO vs PPC: Which Is Better for Your Business?","Blog Article","SEO vs PPC","SEO vs PPC comparison; organic vs paid search; Google Ads vs SEO; PPC or SEO for business","Informational","SEO vs PPC: Which Is Better for Your Business?","46","SEO vs PPC comparison guide: discover differences in speed, cost, long-term ROI, and learn how to build a unified search strategy that maximizes revenue.","154","https://houserobotics.online/seo-vs-ppc-which-is-better-for-your-business/","index, follow","SEO vs PPC: Which Is Better for Your Business?","SEO vs PPC comparison guide: discover differences in speed, cost, long-term ROI, and learn how to build a unified search strategy that maximizes revenue.","https://houserobotics.online/images/seo-vs-ppc-which-is-better-for-your-business.webp","SEO vs PPC: Which Is Better for Your Business?","SEO vs PPC comparison guide: discover differences in speed, cost, long-term ROI, and learn how to build a unified search strategy that maximizes revenue.","https://houserobotics.online/images/seo-vs-ppc-which-is-better-for-your-business.webp","SEO vs PPC: Which Is Better for Your Business?","Article, Organization, BreadcrumbList","PASS"',
  '"https://houserobotics.online/how-google-business-profile-helps-local-businesses/","How Google Business Profile Helps Local Businesses","Blog Article","how Google Business Profile helps local businesses","Google Business Profile benefits; Google Maps marketing; local SEO Google Business; Google 3-pack ranking","Informational","How Google Business Profile Helps Local Businesses | Guide","58","Discover how Google Business Profile drives local visibility, Google Maps 3-Pack rankings, customer trust, and steady inbound phone calls for local businesses.","160","https://houserobotics.online/how-google-business-profile-helps-local-businesses/","index, follow","How Google Business Profile Helps Local Businesses | Guide","Discover how Google Business Profile drives local visibility, Google Maps 3-Pack rankings, customer trust, and steady inbound phone calls for local businesses.","https://houserobotics.online/images/how-google-business-profile-helps-local-businesses.webp","How Google Business Profile Helps Local Businesses | Guide","Discover how Google Business Profile drives local visibility, Google Maps 3-Pack rankings, customer trust, and steady inbound phone calls for local businesses.","https://houserobotics.online/images/how-google-business-profile-helps-local-businesses.webp","How Google Business Profile Helps Local Businesses","Article, Organization, BreadcrumbList","PASS"',
  '"https://houserobotics.online/how-to-improve-your-google-rankings-in-2026/","How to Improve Your Google Rankings in 2026","Blog Article","how to improve your Google rankings in 2026","improve Google rankings 2026; SEO strategy 2026; AI Overviews SEO; Google ranking factors 2026","Informational","How to Improve Google Rankings in 2026 | Full Guide","50","Actionable playbook on improving Google rankings in 2026. Master AI Overviews, semantic entity optimization, Core Web Vitals, and authoritative backlinks.","154","https://houserobotics.online/how-to-improve-your-google-rankings-in-2026/","index, follow","How to Improve Google Rankings in 2026 | Full Guide","Actionable playbook on improving Google rankings in 2026. Master AI Overviews, semantic entity optimization, Core Web Vitals, and authoritative backlinks.","https://houserobotics.online/images/how-to-improve-your-google-rankings-in-2026.webp","How to Improve Google Rankings in 2026 | Full Guide","Actionable playbook on improving Google rankings in 2026. Master AI Overviews, semantic entity optimization, Core Web Vitals, and authoritative backlinks.","https://houserobotics.online/images/how-to-improve-your-google-rankings-in-2026.webp","How to Improve Your Google Rankings in 2026: The Complete Guide","Article, Organization, BreadcrumbList","PASS"'
];

// Insert before the 404 line
const line404Marker = '"https://houserobotics.online/404"';
const idx404 = csv.indexOf(line404Marker);
if (idx404 !== -1) {
  csv = csv.slice(0, idx404) + lines.join('\n') + '\n' + csv.slice(idx404);
} else {
  csv = csv.trim() + '\n' + lines.join('\n') + '\n';
}

fs.writeFileSync(csvPath, csv, 'utf8');
console.log('Appended restored articles to SEO-METADATA-MASTER.csv');
